[package]
name = "vision"
version = "0.0.1"
authors = ["James Lucas <lucasj94@hotmail.co.uk>"]

[dependencies]
hyper = "0.11.9"
tokio-core = "0.1.12"
futures = "0.1.18"
flate2 = "1.0.1"
tar = "0.4"
byteorder = "1"
